data:
  graph:
    data_source: ../data
    field_keys:
      - labels
      - atomic_num
      # - formal_charge
      # - chiral_tag
      - hybridization
      - num_explicit_hs
      - is_aromatic
    fingerprint_dims: 64 # should be same with model's fingerprint_dims & num_layers
    radius: 3             # might be same with model's num_layers
  loader:
    train_batch_size: 1024
    test_batch_size: 1024

model:
  node_emb_dims: 32
  hidden_dims: 32
  fingerprint_dims: 64 # should be same with data's fingerprint_dims & radius
  num_layers: 3         # might be same with model's radius

optimizer:
  lr: !!float 1e-4
  weight_decay: !!float 1e-5

trainer:
  max_epochs: 500
  early_stop: 100